### ISSUE TITLE
Barco Pulse Lens Shift and Menu Commands not working

### ISSUE THREAD

**Issue by ethan-tripp** [bitfocus/companion-module-barco-pulse#1]
All lens shift commands and menu currently not functioning on 3 tested Barco F90-4K13 projectors. No visible changes upon button presses. These units do use the Barco Pulse protocol.  

Power and shutter commands working fine on all projectors, so I at least know the connection is solid. 

MacOS 10.14.5
Browser: Safari

**Comment by McHauge** [comment]
@ethan-tripp I'm looking at this module atm, but can't see what should cause the lens shift buttons to not work correctly, did you set them up yourself, or did you use the preset buttons for it, and also did you just quick press it or did you hold it down?

since it might move very slowly and therefore nothing at all on quick presses.

**Comment by ethan-tripp** [comment]
@McHauge hey, thanks for taking a look. 

I tested out lens shift commands on both presets and creating a command button the normal way. Tried both quick presses and pressing/holding. Did this for a while just to make sure it wasn't trying to shift at a sub-pixel rate. 

Power and shutter commands still working fine. 

I'm currently using Octopus to control lens shift in the meantime. The command I'm using to shift: 

{"jsonrpc": "2.0","method": "optics.lensshift.horizontal.stepreverse","params": {"steps": 1},"id": 18}

**Comment by McHauge** [comment]
kinda makes sense then the module uses: `{"jsonrpc": "2.0","method": "keydispatcher.sendpressevent", "key": "RC_SHIFT_UP", "id": 2}` as the command

**Comment by JeffreyDavidsz** [comment]
Wow that was already a while ago ;-) I've deleted my original file (ended up using the one William already created) and comment out everything that wasn't necessary. The key command is a simulation of the remote. I thought is was tested but I guess not. @McHauge will you change the command?

**Comment by McHauge** [comment]
I'll give in an overlook, any other things missing or commands/options/features, that would be nice to have?

**Comment by JeffreyDavidsz** [comment]
I remember that I did not create feedback a I thought that was a bit to much, but presets where handy

**Comment by ethan-tripp** [comment]
Feedback to know if/when power or shutter is active would be fantastic! i.e. on/off buttons that accurately showed current power/shutter status. Many times our projectors are turned on/off and shuttered using an external control platform, so Companion never knows current status. 

Also, enabling test patterns and adjusting focus would be useful.

**Comment by McHauge** [comment]
@ethan-tripp I'll give it a look, and see what I can do, I'll be back in a few days. If you come up with other suggestions please post them.

**Comment by McHauge** [comment]
@ethan-tripp Hi, I got a compiled version for Windows now, with more presets, and lens movement, focus, zoom and all buttons for the remote. Gonna take a look at feedbacks next and maybe adding more inputs and test patterns.

You can get the Test build, with the new Streamdeck driver installed here: [Download at OneDrive](https://1drv.ms/f/s!AtUYbExJseNtlK56u-n71V_UcLDe7g)
