### ISSUE TITLE
[feature] Feedback from projector

### ISSUE THREAD

**Issue by VuiMuich** [bitfocus/companion-module-barco-pulse#2]
Hi,

I saw you already started preparation for feedback from projectors, is there any progress been happening locally at your side?
We really would appreciate this feature, thaugh it is a bit hard for us to contribute to this module, as our projectors are in a local offline network and our computers which are connected to the internet are heavily restricted, so there as basically no possibility to do dev work.

Thanks, though for your work already done..

**Comment by josephdadams** [comment]
I added feedback for power state (ready, standby, on, off, deconditioning) in the latest release for companion v3.

**Comment by VuiMuich** [comment]
Awesome, thanks!
